In [1]:
import pynq
from pynq import allocate
from pynq.lib.video import *

ol = pynq.Overlay('rasterization9/vitis_design.bit')

ip = ol.rasterization_1

In [2]:
import os
import sys
import cv2
import torch
import torch.nn.functional as F
import numpy as np
import socket
import time

In [3]:
_BASE_DIR = os.getcwd()
sys.path.insert(0, _BASE_DIR)

from utils.rasterization import GaussianRasterizer as Renderer
from utils.rasterization import GaussianRasterizationSettings as Camera
from utils.common_helpers import *
from utils.recon_helpers import *
from utils.slam_helpers import *

In [4]:
from pynq.lib.video import *
displayport = DisplayPort()
print(displayport.modes)
mode = displayport.modes[0]
displayport.configure(VideoMode(1920, 1200, 24), PIXEL_RGB)
displayport.start()

[VideoMode: width=1920 height=1200 bpp=24 fps=60, VideoMode: width=1920 height=1080 bpp=24 fps=60, VideoMode: width=1920 height=1080 bpp=24 fps=60, VideoMode: width=1920 height=1080 bpp=24 fps=60, VideoMode: width=1920 height=1080 bpp=24 fps=50, VideoMode: width=1680 height=1050 bpp=24 fps=60, VideoMode: width=1440 height=900 bpp=24 fps=60, VideoMode: width=1280 height=960 bpp=24 fps=60, VideoMode: width=1280 height=800 bpp=24 fps=60, VideoMode: width=1280 height=720 bpp=24 fps=60, VideoMode: width=1280 height=720 bpp=24 fps=60, VideoMode: width=1280 height=720 bpp=24 fps=50, VideoMode: width=1024 height=768 bpp=24 fps=60, VideoMode: width=800 height=600 bpp=24 fps=60, VideoMode: width=800 height=600 bpp=24 fps=56, VideoMode: width=640 height=480 bpp=24 fps=60, VideoMode: width=640 height=480 bpp=24 fps=60]


In [5]:
def load_camera(cfg, scene_path):
    all_params = dict(np.load(scene_path, allow_pickle=True))
    params = all_params
    org_width = params['width']
    org_height = params['height']
    w2c = torch.eye(4)
    intrinsics = params['intrinsics']
    k = intrinsics[:3, :3]

    # Scale intrinsics to match the visualization resolution
    k[0, :] *= cfg['viz_w'] / org_width
    k[1, :] *= cfg['viz_h'] / org_height
    return w2c, k

def load_scene_data(scene_path, first_frame_w2c):
    # Load Scene Data
    all_params = dict(np.load(scene_path, allow_pickle=True))
    all_params = {k: torch.tensor(all_params[k]).cpu().float() for k in all_params.keys()}
    first_frame_w2c = torch.tensor(first_frame_w2c).cpu().float()

    keys = [k for k in all_params.keys() if
            k in ['means3D', 'colors_precomp', 'opacities', 'scales', 'means2D']]

    params = all_params
    for k in keys:
        if not isinstance(all_params[k], torch.Tensor):
            params[k] = torch.tensor(all_params[k]).cpu().float()
        else:
            params[k] = all_params[k].cpu().float()
    
    opacities = torch.sigmoid(params['logit_opacities'])
    rendervar = {
        'md_1_for': torch.cat([params['means3D'], params["scales"], params['rgb_colors'], opacities ], dim=1).contiguous(),
        'means2D': torch.zeros_like(params['means3D'], requires_grad=True, device="cpu") + 0,
    }
    params['thresholds'] = [0.3, 0.481, 0.556, 0.613, 0.661, 0.704, 0.743, 0.778, 0.811, 0.842, 0.872, 0.899, 0.926, 0.952, 0.976, 1.0, 1.011, 1.023, 1.034, 1.045, 1.057, 1.068, 1.08, 1.091, 1.102, 1.114, 1.125, 1.136, 1.148, 1.159, 1.17, 1.182, 1.193, 1.205, 1.216, 1.227, 1.239, 1.25, 1.261, 1.273, 1.284, 1.295, 1.307, 1.318, 1.33, 1.341, 1.352, 1.364, 1.375, 1.386, 1.398, 1.409, 1.42, 1.432, 1.443, 1.455, 1.466, 1.477, 1.489, 1.5, 1.511, 1.523, 1.534, 1.545, 1.557, 1.568, 1.58, 1.591, 1.602, 1.614, 1.625, 1.636, 1.648, 1.659, 1.67, 1.682, 1.693, 1.705, 1.716, 1.727, 1.739, 1.75, 1.761, 1.773, 1.784, 1.795, 1.807, 1.818, 1.83, 1.841, 1.852, 1.864, 1.875, 1.886, 1.898, 1.909, 1.92, 1.932, 1.943, 1.955, 1.966, 1.977, 1.989, 2.0, 2.011, 2.023, 2.034, 2.045, 2.057, 2.068, 2.08, 2.091, 2.102, 2.114, 2.125, 2.136, 2.148, 2.159, 2.17, 2.182, 2.193, 2.205, 2.216, 2.227, 2.239, 2.25, 2.261, 2.273, 2.284, 2.295, 2.307, 2.318, 2.33, 2.341, 2.352, 2.364, 2.375, 2.386, 2.398, 2.409, 2.42, 2.432, 2.443, 2.455, 2.466, 2.477, 2.489, 2.5, 2.511, 2.523, 2.534, 2.545, 2.557, 2.568, 2.58, 2.591, 2.602, 2.614, 2.625, 2.636, 2.648, 2.659, 2.67, 2.682, 2.693, 2.705, 2.716, 2.727, 2.739, 2.75, 2.761, 2.773, 2.784, 2.795, 2.807, 2.818, 2.83, 2.841, 2.852, 2.864, 2.875, 2.886, 2.898, 2.909, 2.92, 2.932, 2.943, 2.955, 2.966, 2.977, 2.989, 3.0, 3.057, 3.115, 3.174, 3.234, 3.296, 3.358, 3.422, 3.487, 3.553, 3.621, 3.69, 3.76, 3.831, 3.904, 3.978, 4.054, 4.131, 4.209, 4.289, 4.37, 4.453, 4.538, 4.624, 4.712, 4.801, 4.893, 4.986, 5.08, 5.177, 5.275, 5.375, 5.477, 5.581, 5.687, 5.795, 5.905, 6.017, 6.132, 6.248, 6.367, 6.488, 6.611, 6.736, 6.864, 6.995, 7.128, 7.263, 7.401, 7.541, 7.685, 7.831, 7.979, 8.131, 8.285, 8.442, 8.603, 8.766, 8.933, 9.102, 9.275, 9.451, 9.631, 9.814, 9.999]
    return rendervar , params['thresholds']

def render(ip, w2c, k, thresholds, timestep_data, cfg):
    with torch.no_grad():
        cam = setup_camera(cfg['viz_w'], cfg['viz_h'], thresholds, k, w2c, cfg['viz_near'], cfg['viz_far'])
        im, _, _ = Renderer(ip=ip, raster_settings=cam)(**timestep_data)
        return im.detach().numpy()
    
def get_new_cam(data):
    try:
        # 将字节数据解码为字符串
        data_str = data.decode('utf-8').strip()
        print(f"接收到的数据: {data_str}")
        
        # 检查数据格式是否正确
        if data_str.startswith("w2c_matrix:"):
            matrix_str = data_str.replace("w2c_matrix:", "")
            
            float_strs = matrix_str.split(",")
            
            if len(float_strs) == 16:
                # 将字符串转换为浮点数并重塑为4x4矩阵
                float_array = [float(x) for x in float_strs]
                w2c = torch.tensor(float_array).reshape(4, 4).float()
                print("成功解析w2c矩阵:")
                print(w2c)
                return w2c
            else:
                print(f"警告: 矩阵元素数量不正确,期望16个,实际收到{len(float_strs)}个")
        else:
            print(f"警告: 数据格式不正确,期望以'w2c_matrix:'开头")
            
    except Exception as e:
        print(f"解析w2c矩阵时出错: {e}")
    
    # 如果解析失败，返回None，让调用者决定如何处理
    return None

In [6]:
def visualize_sequence(ip, scene_path, cfg, send_sock, recv_sock):
    
    print(f"服务器已启动，监听端口 {server_address[1]}...")

    current_w2c, k = load_camera(cfg, scene_path)
    scene_data, thresholds = load_scene_data(scene_path, current_w2c)
    im = render(ip, current_w2c, k, thresholds, scene_data, cfg)
    
#     im = im.reshape(360, 480, 3) * 255
#     im[im > 255] = 255
#     im[im < 0] = 0
#     img_uint8 = im.astype(np.uint8)
#     img_RGB = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
#     frame = displayport.newframe()
#     np.copyto(frame, cv2.resize(img_RGB, (1920,1200)))
#     displayport.writeframe(frame)

    im = im.reshape(360, 480, 3) * 255
    im[im > 255] = 255
    im[im < 0] = 0
    img_uint8 = im.astype(np.uint8)
    img_RGB = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
    # 获取原始图像尺寸
    orig_height, orig_width = img_RGB.shape[:2]
    orig_height *= 3
    orig_width *= 3
    # 创建黑色背景帧
    img_RGB = cv2.resize(img_RGB, (orig_width,orig_height))
    frame = displayport.newframe()
    frame[:] = 0  # 填充黑色
    # 计算居中位置
    start_x = (1920 - orig_width) // 2
    start_y = (1200 - orig_height) // 2
    # 将图像复制到帧的中央位置
    frame[start_y:start_y+orig_height, start_x:start_x+orig_width] = img_RGB
    displayport.writeframe(frame)

   
    t =time.time()
    while True:
        send_sock.sendto(b'1', ('192.168.0.142', 8777))
        print(f"已向 192.168.5.7 发送确认消息")
        
        try:
            data, address = recv_sock.recvfrom(1024)

            new_w2c = get_new_cam(data)

            im = render(ip, new_w2c, k, thresholds, scene_data, cfg)
            
#             im = im.reshape(360, 480, 3) * 255
#             im[im > 255] = 255
#             im[im < 0] = 0
#             img_uint8 = im.astype(np.uint8)
#             img_RGB = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
#             frame = displayport.newframe()
#             np.copyto(frame, cv2.resize(img_RGB, (1920,1200)))
#             displayport.writeframe(frame)

            im = im.reshape(360, 480, 3) * 255
            im[im > 255] = 255
            im[im < 0] = 0
            img_uint8 = im.astype(np.uint8)
            img_RGB = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
            # 获取原始图像尺寸
            orig_height, orig_width = img_RGB.shape[:2]
            orig_height *= 3
            orig_width *= 3
            img_RGB = cv2.resize(img_RGB, (orig_width,orig_height))
            # 创建黑色背景帧
            frame = displayport.newframe()
            frame[:] = 0  # 填充黑色
            # 计算居中位置
            start_x = (1920 - orig_width) // 2
            start_y = (1200 - orig_height) // 2
            # 将图像复制到帧的中央位置
            frame[start_y:start_y+orig_height, start_x:start_x+orig_width] = img_RGB
            displayport.writeframe(frame)
        
        except socket.timeout:
            # 2秒内没有收到回复，继续下一次循环
            print("等待回复超时，继续下一次发送")
            continue
        except Exception as e:
            # 处理其他可能的异常
           
            print(f"接收数据时发生错误: {e}")
            continue
            
#         if time.time() - t > 5 :break
            

In [7]:
results_dir = os.path.join(_BASE_DIR, "experiments")
scene_path = os.path.join(results_dir, "params.npz")

if not os.path.exists(scene_path):
    print(f"错误: 找不到场景数据文件 {scene_path}")
    sys.exit(1)

# 创建默认配置
class DefaultConfig:
    def __init__(self):
        self.config = {
            "workdir": _BASE_DIR,
            "run_name": "experiments",
            "seed": 42,
            "viz": {
                "viz_w": 640,
                "viz_h": 480,
                "viz_near": 0.01,
                "viz_far": 100,
                "view_scale": 2.0,
                "visualize_cams": False,
                "offset_first_viz_cam": False,
                "render_mode": "centers",
                "show_sil": False
            }
        }

experiment = DefaultConfig()
viz_cfg = experiment.config["viz"]

# 输出目录
output_dir = os.path.join(_BASE_DIR, "rendered_output")

# 创建socket并绑定地址和端口
# 创建两个socket：一个用于发送，一个用于接收
send_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
recv_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
# 设置接收socket的超时
recv_sock.settimeout(2)
# 只绑定接收socket到8778端口
server_address = ('0.0.0.0', 8778)
recv_sock.bind(server_address)

# 可视化序列
visualize_sequence(ip, scene_path, viz_cfg, send_sock, recv_sock)

服务器已启动，监听端口 8778...
trying to : pre grouping...


/tmp/ipykernel_9080/174971674.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  first_frame_w2c = torch.tensor(first_frame_w2c).cpu().float()
/home/xilinx/jupyter_notebooks/SGSAM/utils/recon_helpers.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w2c = torch.tensor(w2c).float()


buffers take : 162.13583946228027 ms    means3D 5.662679672241211 ms    allocate 12.57014274597168 ms    temp_mem_buffer/sortouts_buffer 143.90206336975098 ms
Done! pre_grouping_ip takes : 52.71434783935547 ms
trying to : forward...
buffers take : 177.77585983276367 ms    sum acc_size 152.1279811859131 ms
render ip working time :  122.91121482849121 ms

time pg  273.4043598175049 ms
time fw  303.3618927001953 ms
time ol_forward  594.8340892791748 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
trying to : pre grouping...
buffers take : 101.83477401733398 ms    means3D 3.7119388580322266 ms    allocate 7.042884826660156 ms    temp_mem_buffer/sortouts_buffer 91.07851982116699 ms
Done! pre_grouping_ip takes : 52.54220962524414 ms
trying 

buffers take : 87.76617050170898 ms    means3D 2.6373863220214844 ms    allocate 7.360219955444336 ms    temp_mem_buffer/sortouts_buffer 77.76761054992676 ms
Done! pre_grouping_ip takes : 53.151845932006836 ms
trying to : forward...
buffers take : 174.18575286865234 ms    sum acc_size 148.15139770507812 ms
render ip working time :  164.42155838012695 ms

time pg  160.1402759552002 ms
time fw  341.3078784942627 ms
time ol_forward  519.456148147583 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,0.819152,-0.573576,0.000000,0.000000,0.573576,0.819152,0.200000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.8192, -0.5736,  0.0000],
        [ 0.0000,  0.5736,  0.8192,  0.2000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 91.18366241455078 ms    means3D 5.977153778076172 ms    allocate 7.1773529052734375 ms    temp_mem_buffer/sortouts_buffer

接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.5931510925293 ms    means3D 2.676725387573242 ms    allocate 7.344961166381836 ms    temp_mem_buffer/sortouts_buffer 76.56979560852051 ms
Done! pre_grouping_ip takes : 53.14040184020996 ms
trying to : forward...
buffers take : 177.06537246704102 ms    sum acc_size 149.82891082763672 ms
render ip working time :  180.54914474487305 ms

time pg  158.2334041595459 ms
time fw  360.20922660827637 ms
time ol_forward  536.452054977417 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.0000

buffers take : 176.06329917907715 ms    sum acc_size 149.7809886932373 ms
render ip working time :  180.5422306060791 ms

time pg  159.33918952941895 ms
time fw  359.2972755432129 ms
time ol_forward  536.6573333740234 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.06848526000977 ms    means3D 2.6252269744873047 ms    allocate 8.19253921508789 ms    temp_mem_buffer/sortouts_buffer 77.24928855895996 ms
Done! pre_grouping_ip takes : 53.29728126525879 ms
trying to : forward...
buffers take : 174.40080642700195 ms    sum acc_size 148.2522487640381 ms
render ip working time :  180.56035041809082 ms

time pg  160.

trying to : pre grouping...
buffers take : 89.78724479675293 ms    means3D 5.997419357299805 ms    allocate 7.27534294128418 ms    temp_mem_buffer/sortouts_buffer 76.51281356811523 ms
Done! pre_grouping_ip takes : 53.13873291015625 ms
trying to : forward...
buffers take : 176.41282081604004 ms    sum acc_size 149.43242073059082 ms
render ip working time :  180.56440353393555 ms

time pg  161.51666641235352 ms
time fw  359.7989082336426 ms
time ol_forward  539.2658710479736 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.83483505249023 ms    means3D 2.6912689208984375 ms    allocate 7.465839385986328 ms    te

tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.91694450378418 ms    means3D 6.04701042175293 ms    allocate 7.310628890991211 ms    temp_mem_buffer/sortouts_buffer 76.55787467956543 ms
Done! pre_grouping_ip takes : 53.13444137573242 ms
trying to : forward...
buffers take : 176.5894889831543 ms    sum acc_size 149.46651458740234 ms
render ip working time :  180.5558204650879 ms

time pg  161.53883934020996 ms
time fw  359.9841594696045 ms
time ol_forward  539.4976139068604 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],

buffers take : 174.4222640991211 ms    sum acc_size 148.11134338378906 ms
render ip working time :  180.55391311645508 ms

time pg  160.83025932312012 ms
time fw  357.6512336730957 ms
time ol_forward  536.515474319458 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.80438995361328 ms    means3D 2.6912689208984375 ms    allocate 7.240056991577148 ms    temp_mem_buffer/sortouts_buffer 76.87163352966309 ms
Done! pre_grouping_ip takes : 53.12657356262207 ms
trying to : forward...
buffers take : 173.34842681884766 ms    sum acc_size 147.40848541259766 ms
render ip working time :  180.56654930114746 ms

time pg  15

buffers take : 176.4063835144043 ms    sum acc_size 149.3070125579834 ms
render ip working time :  180.55295944213867 ms

time pg  159.4550609588623 ms
time fw  359.5726490020752 ms
time ol_forward  537.1084213256836 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.34750747680664 ms    means3D 2.618074417114258 ms    allocate 7.225990295410156 ms    temp_mem_buffer/sortouts_buffer 77.50225067138672 ms
Done! pre_grouping_ip takes : 53.29251289367676 ms
trying to : forward...
buffers take : 173.78664016723633 ms    sum acc_size 147.84812927246094 ms
render ip working time :  180.5565357208252 ms

time pg  160.0

buffers take : 89.20121192932129 ms    means3D 5.332469940185547 ms    allocate 7.3947906494140625 ms    temp_mem_buffer/sortouts_buffer 76.47204399108887 ms
Done! pre_grouping_ip takes : 53.14517021179199 ms
trying to : forward...
buffers take : 174.51739311218262 ms    sum acc_size 148.24199676513672 ms
render ip working time :  180.56035041809082 ms

time pg  162.05930709838867 ms
time fw  357.81002044677734 ms
time ol_forward  537.8186702728271 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.04423904418945 ms    means3D 2.7141571044921875 ms    allocate 7.443666458129883 ms    temp_mem_buffer/sortouts_bu

buffers take : 89.12205696105957 ms    means3D 4.800558090209961 ms    allocate 7.401943206787109 ms    temp_mem_buffer/sortouts_buffer 76.91836357116699 ms
Done! pre_grouping_ip takes : 53.14445495605469 ms
trying to : forward...
buffers take : 174.07679557800293 ms    sum acc_size 147.75705337524414 ms
render ip working time :  180.55438995361328 ms

time pg  162.06955909729004 ms
time fw  357.3036193847656 ms
time ol_forward  537.4128818511963 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.61939811706543 ms    means3D 5.975484848022461 ms    allocate 7.30586051940918 ms    temp_mem_buffer/sortouts_buffer

接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.72532844543457 ms    means3D 5.278110504150391 ms    allocate 7.058143615722656 ms    temp_mem_buffer/sortouts_buffer 76.38740539550781 ms
Done! pre_grouping_ip takes : 53.788185119628906 ms
trying to : forward...
buffers take : 176.28931999206543 ms    sum acc_size 149.06764030456543 ms
render ip working time :  180.56392669677734 ms

time pg  161.02147102355957 ms
time fw  359.4391345977783 ms
time ol_forward  538.4097099304199 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.0

buffers take : 174.00813102722168 ms    sum acc_size 148.06127548217773 ms
render ip working time :  180.56607246398926 ms

time pg  162.445068359375 ms
time fw  357.2728633880615 ms
time ol_forward  537.6904010772705 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.41347694396973 ms    means3D 4.894733428955078 ms    allocate 7.136344909667969 ms    temp_mem_buffer/sortouts_buffer 76.38096809387207 ms
Done! pre_grouping_ip takes : 53.23624610900879 ms
trying to : forward...
buffers take : 175.0035285949707 ms    sum acc_size 148.61631393432617 ms
render ip working time :  180.5572509765625 ms

time pg  160.9

buffers take : 176.56517028808594 ms    sum acc_size 149.4302749633789 ms
render ip working time :  180.56106567382812 ms

time pg  159.27720069885254 ms
time fw  359.7533702850342 ms
time ol_forward  537.003755569458 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.35346794128418 ms    means3D 2.565622329711914 ms    allocate 7.151126861572266 ms    temp_mem_buffer/sortouts_buffer 77.63528823852539 ms
Done! pre_grouping_ip takes : 53.299665451049805 ms
trying to : forward...
buffers take : 173.44117164611816 ms    sum acc_size 147.507905960083 ms
render ip working time :  180.5558204650879 ms

time pg  159.8

tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.41276168823242 ms    means3D 4.626989364624023 ms    allocate 7.400035858154297 ms    temp_mem_buffer/sortouts_buffer 76.38430595397949 ms
Done! pre_grouping_ip takes : 53.388118743896484 ms
trying to : forward...
buffers take : 181.22363090515137 ms    sum acc_size 154.0844440460205 ms
render ip working time :  180.56344985961914 ms

time pg  160.4142189025879 ms
time fw  364.41969871520996 ms
time ol_forward  542.799711227417 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500

buffers take : 173.89273643493652 ms    sum acc_size 147.78780937194824 ms
render ip working time :  180.55272102355957 ms

time pg  160.23564338684082 ms
time fw  357.1178913116455 ms
time ol_forward  535.4130268096924 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.54134178161621 ms    means3D 3.669261932373047 ms    allocate 7.427692413330078 ms    temp_mem_buffer/sortouts_buffer 76.44295692443848 ms
Done! pre_grouping_ip takes : 53.79652976989746 ms
trying to : forward...
buffers take : 181.42342567443848 ms    sum acc_size 154.19721603393555 ms
render ip working time :  180.54485321044922 ms

time pg  1

buffers take : 88.90724182128906 ms    means3D 3.533601760864258 ms    allocate 7.287263870239258 ms    temp_mem_buffer/sortouts_buffer 78.08518409729004 ms
Done! pre_grouping_ip takes : 53.307533264160156 ms
trying to : forward...
buffers take : 173.47455024719238 ms    sum acc_size 147.51005172729492 ms
render ip working time :  180.56845664978027 ms

time pg  161.53931617736816 ms
time fw  356.7488193511963 ms
time ol_forward  536.2734794616699 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.83898162841797 ms    means3D 6.011962890625 ms    allocate 7.398843765258789 ms    temp_mem_buffer/sortouts_buffer 

接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.6243839263916 ms    means3D 2.8612613677978516 ms    allocate 7.384300231933594 ms    temp_mem_buffer/sortouts_buffer 76.37739181518555 ms
Done! pre_grouping_ip takes : 53.12538146972656 ms
trying to : forward...
buffers take : 176.10573768615723 ms    sum acc_size 149.0468978881836 ms
render ip working time :  180.5586814880371 ms

time pg  158.15091133117676 ms
time fw  359.2660427093506 ms
time ol_forward  535.4726314544678 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.0000

buffers take : 173.9182472229004 ms    sum acc_size 147.97353744506836 ms
render ip working time :  180.56368827819824 ms

time pg  159.89017486572266 ms
time fw  357.13839530944824 ms
time ol_forward  534.9833965301514 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.086824,0.866026,-0.492404,0.000000,0.150384,0.500000,0.852869,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0868,  0.8660, -0.4924,  0.0000],
        [ 0.1504,  0.5000,  0.8529,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.7300968170166 ms    means3D 4.4231414794921875 ms    allocate 7.769584655761719 ms    temp_mem_buffer/sortouts_buffer 76.53546333312988 ms
Done! pre_grouping_ip takes : 53.15375328063965 ms
trying to : forward...
buffers take : 176.09715461730957 ms    sum acc_size 149.19400215148926 ms
render ip working time :  180.55272102355957 ms

time pg  1

buffers take : 173.40779304504395 ms    sum acc_size 147.48573303222656 ms
render ip working time :  128.39484214782715 ms

time pg  159.9099636077881 ms
time fw  304.43882942199707 ms
time ol_forward  482.35416412353516 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.2500],
        [0.0000, 0.0000, 0.0000, 1.0000]])
trying to : pre grouping...
buffers take : 89.0035629272461 ms    means3D 3.583669662475586 ms    allocate 7.128238677978516 ms    temp_mem_buffer/sortouts_buffer 78.29022407531738 ms
Done! pre_grouping_ip takes : 53.003787994384766 ms
trying to : forward...
buffers take : 174.6656894683838 ms    sum acc_size 148.4091281890869 ms
render ip working time :  130.2964687347412 ms

time pg  161.33761405944824 ms


buffers take : 89.13826942443848 ms    means3D 5.091428756713867 ms    allocate 7.286787033081055 ms    temp_mem_buffer/sortouts_buffer 76.75838470458984 ms
Done! pre_grouping_ip takes : 53.2076358795166 ms
trying to : forward...
buffers take : 175.54783821105957 ms    sum acc_size 148.44322204589844 ms
render ip working time :  174.95393753051758 ms

time pg  161.55171394348145 ms
time fw  353.1656265258789 ms
time ol_forward  532.7181816101074 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.50455284118652 ms    means3D 4.666805267333984 ms    allocate 7.321596145629883 ms    temp_mem_buffer/sortouts_buffer

接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.72039413452148 ms    means3D 4.057884216308594 ms    allocate 7.09223747253418 ms    temp_mem_buffer/sortouts_buffer 76.5690803527832 ms
Done! pre_grouping_ip takes : 53.22074890136719 ms
trying to : forward...
buffers take : 175.81963539123535 ms    sum acc_size 148.76985549926758 ms
render ip working time :  174.93629455566406 ms

time pg  159.3625545501709 ms
time fw  353.58428955078125 ms
time ol_forward  531.0149192810059 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.0000

buffers take : 173.9022731781006 ms    sum acc_size 147.6602554321289 ms
render ip working time :  174.93152618408203 ms

time pg  160.8290672302246 ms
time fw  351.5312671661377 ms
time ol_forward  530.3409099578857 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.54508399963379 ms    means3D 4.920244216918945 ms    allocate 7.165670394897461 ms    temp_mem_buffer/sortouts_buffer 76.45773887634277 ms
Done! pre_grouping_ip takes : 53.214311599731445 ms
trying to : forward...
buffers take : 176.4845848083496 ms    sum acc_size 149.41167831420898 ms
render ip working time :  174.9286651611328 ms

time pg  160.1

buffers take : 176.81074142456055 ms    sum acc_size 149.74379539489746 ms
render ip working time :  174.9410629272461 ms

time pg  158.87951850891113 ms
time fw  354.33244705200195 ms
time ol_forward  531.205415725708 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.98725700378418 ms    means3D 2.8281211853027344 ms    allocate 7.231712341308594 ms    temp_mem_buffer/sortouts_buffer 76.92599296569824 ms
Done! pre_grouping_ip takes : 53.238630294799805 ms
trying to : forward...
buffers take : 175.75311660766602 ms    sum acc_size 148.6670970916748 ms
render ip working time :  174.9427318572998 ms

time pg  15

buffers take : 88.73653411865234 ms    means3D 4.8503875732421875 ms    allocate 7.286787033081055 ms    temp_mem_buffer/sortouts_buffer 76.59792900085449 ms
Done! pre_grouping_ip takes : 53.19786071777344 ms
trying to : forward...
buffers take : 173.90799522399902 ms    sum acc_size 147.6426124572754 ms
render ip working time :  174.9289035797119 ms

time pg  161.12065315246582 ms
time fw  351.482629776001 ms
time ol_forward  530.5206775665283 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.49897575378418 ms    means3D 3.004312515258789 ms    allocate 7.114648818969727 ms    temp_mem_buffer/sortouts_buffer 

接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,-0.000000,0.906308,-0.422618,0.000000,0.000000,0.422618,0.906308,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [-0.0000,  0.9063, -0.4226,  0.0000],
        [ 0.0000,  0.4226,  0.9063,  0.4000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.03813362121582 ms    means3D 5.601167678833008 ms    allocate 7.062435150146484 ms    temp_mem_buffer/sortouts_buffer 76.37310028076172 ms
Done! pre_grouping_ip takes : 53.17854881286621 ms
trying to : forward...
buffers take : 176.4214038848877 ms    sum acc_size 149.3813991546631 ms
render ip working time :  184.8304271697998 ms

time pg  160.49528121948242 ms
time fw  364.0730381011963 ms
time ol_forward  542.5364971160889 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,-0.000000,0.906308,-0.422618,0.000000,0.000000,0.422618,0.906308,0.400000,0.000000,

buffers take : 175.5850315093994 ms    sum acc_size 148.39506149291992 ms
render ip working time :  174.940824508667 ms

time pg  158.82635116577148 ms
time fw  353.107213973999 ms
time ol_forward  529.8452377319336 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.984808,0.000000,-0.173648,0.000000,-0.073387,0.906308,-0.416198,0.000000,0.157379,0.422618,0.892539,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9848,  0.0000, -0.1736,  0.0000],
        [-0.0734,  0.9063, -0.4162,  0.0000],
        [ 0.1574,  0.4226,  0.8925,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.41021156311035 ms    means3D 2.6712417602539062 ms    allocate 7.14874267578125 ms    temp_mem_buffer/sortouts_buffer 77.58903503417969 ms
Done! pre_grouping_ip takes : 53.399085998535156 ms
trying to : forward...
buffers take : 174.15976524353027 ms    sum acc_size 148.23079109191895 ms
render ip working time :  174.9427318572998 ms

time pg  159.9

buffers take : 86.74120903015137 ms    means3D 2.661466598510742 ms    allocate 7.335662841796875 ms    temp_mem_buffer/sortouts_buffer 76.74288749694824 ms
Done! pre_grouping_ip takes : 53.10177803039551 ms
trying to : forward...
buffers take : 173.77567291259766 ms    sum acc_size 147.75991439819336 ms
render ip working time :  184.5552921295166 ms

time pg  159.1176986694336 ms
time fw  361.1330986022949 ms
time ol_forward  538.2916927337646 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,0.866026,-0.500000,0.000000,0.000000,0.500000,0.866026,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.8660, -0.5000,  0.0000],
        [ 0.0000,  0.5000,  0.8660,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.84515953063965 ms    means3D 2.689361572265625 ms    allocate 7.4367523193359375 ms    temp_mem_buffer/sortouts_buffer 7

buffers take : 89.39051628112793 ms    means3D 5.597591400146484 ms    allocate 7.366180419921875 ms    temp_mem_buffer/sortouts_buffer 76.42531394958496 ms
Done! pre_grouping_ip takes : 53.17807197570801 ms
trying to : forward...
buffers take : 178.85088920593262 ms    sum acc_size 152.88066864013672 ms
render ip working time :  157.68194198608398 ms

time pg  161.76247596740723 ms
time fw  339.45560455322266 ms
time ol_forward  519.5889472961426 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,0.819152,-0.573577,0.000000,0.000000,0.573577,0.819152,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.8192, -0.5736,  0.0000],
        [ 0.0000,  0.5736,  0.8192,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.02311325073242 ms    means3D 5.37562370300293 ms    allocate 7.349252700805664 ms    temp_mem_buffer/sortouts_buffer 

buffers take : 87.53538131713867 ms    means3D 2.685070037841797 ms    allocate 7.316350936889648 ms    temp_mem_buffer/sortouts_buffer 77.53276824951172 ms
Done! pre_grouping_ip takes : 52.99091339111328 ms
trying to : forward...
buffers take : 173.96116256713867 ms    sum acc_size 148.00763130187988 ms
render ip working time :  146.00157737731934 ms

time pg  159.72232818603516 ms
time fw  322.6895332336426 ms
time ol_forward  500.47969818115234 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,0.000000,0.000000,0.866026,-0.500000,0.000000,0.000000,0.500000,0.866026,0.050000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.8660, -0.5000,  0.0000],
        [ 0.0000,  0.5000,  0.8660,  0.0500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.55040168762207 ms    means3D 2.62451171875 ms    allocate 7.241487503051758 ms    temp_mem_buffer/sortouts_buffer 77.

buffers take : 88.29855918884277 ms    means3D 3.6084651947021484 ms    allocate 7.111310958862305 ms    temp_mem_buffer/sortouts_buffer 77.57759094238281 ms
Done! pre_grouping_ip takes : 53.106069564819336 ms
trying to : forward...
buffers take : 173.2959747314453 ms    sum acc_size 147.30238914489746 ms
render ip working time :  152.43124961853027 ms

time pg  160.5839729309082 ms
time fw  328.50122451782227 ms
time ol_forward  507.07030296325684 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.939693,0.000000,-0.342020,0.000000,-0.171010,0.866026,-0.469846,0.000000,0.296198,0.500000,0.813798,0.000000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9397,  0.0000, -0.3420,  0.0000],
        [-0.1710,  0.8660, -0.4698,  0.0000],
        [ 0.2962,  0.5000,  0.8138,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 90.40188789367676 ms    means3D 5.584001541137695 ms    allocate 7.327795028686523 ms    temp_mem_buffer/sortouts_buf

buffers take : 90.65079689025879 ms    means3D 4.858970642089844 ms    allocate 8.31913948059082 ms    temp_mem_buffer/sortouts_buffer 77.47125625610352 ms
Done! pre_grouping_ip takes : 53.09891700744629 ms
trying to : forward...
buffers take : 178.89761924743652 ms    sum acc_size 152.8494358062744 ms
render ip working time :  158.07271003723145 ms

time pg  162.98556327819824 ms
time fw  339.6434783935547 ms
time ol_forward  520.5588340759277 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.866026,0.000000,-0.500000,0.000000,-0.250000,0.866026,-0.433013,0.000000,0.433013,0.500000,0.750000,0.100000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.8660,  0.0000, -0.5000,  0.0000],
        [-0.2500,  0.8660, -0.4330,  0.0000],
        [ 0.4330,  0.5000,  0.7500,  0.1000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.76767349243164 ms    means3D 2.959728240966797 ms    allocate 7.279872894287109 ms    temp_mem_buffer/sortouts_buffer 

buffers take : 87.57662773132324 ms    means3D 3.8340091705322266 ms    allocate 7.357597351074219 ms    temp_mem_buffer/sortouts_buffer 76.38335227966309 ms
Done! pre_grouping_ip takes : 53.36475372314453 ms
trying to : forward...
buffers take : 174.2088794708252 ms    sum acc_size 148.21147918701172 ms
render ip working time :  158.65612030029297 ms

time pg  160.10475158691406 ms
time fw  335.48450469970703 ms
time ol_forward  513.5602951049805 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.866026,0.000000,-0.500000,0.050000,-0.250000,0.866026,-0.433013,0.000000,0.433013,0.500000,0.750000,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.8660,  0.0000, -0.5000,  0.0500],
        [-0.2500,  0.8660, -0.4330,  0.0000],
        [ 0.4330,  0.5000,  0.7500,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.37421035766602 ms    means3D 2.6810169219970703 ms    allocate 7.1201324462890625 ms    temp_mem_buffer/sortouts_bu

接收到的数据: w2c_matrix:0.866026,0.000000,-0.500000,0.050000,-0.250000,0.866026,-0.433013,0.000000,0.433013,0.500000,0.750001,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.8660,  0.0000, -0.5000,  0.0500],
        [-0.2500,  0.8660, -0.4330,  0.0000],
        [ 0.4330,  0.5000,  0.7500,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.77911758422852 ms    means3D 3.062009811401367 ms    allocate 7.384538650512695 ms    temp_mem_buffer/sortouts_buffer 76.33113861083984 ms
Done! pre_grouping_ip takes : 53.30228805541992 ms
trying to : forward...
buffers take : 175.7519245147705 ms    sum acc_size 148.7264633178711 ms
render ip working time :  158.66422653198242 ms

time pg  158.42890739440918 ms
time fw  336.9903564453125 ms
time ol_forward  513.3836269378662 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.866026,0.000000,-0.500000,0.050000,-0.250000,0.866026,-0.433013,0.000000,0.433013,0.500000,0.750001,0.300000,0.0000

buffers take : 173.76971244812012 ms    sum acc_size 147.77159690856934 ms
render ip working time :  163.3625030517578 ms

time pg  159.05308723449707 ms
time fw  339.78819847106934 ms
time ol_forward  516.7591571807861 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.939693,0.000000,-0.342020,-0.100000,-0.171010,0.866026,-0.469846,0.000000,0.296198,0.500000,0.813798,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9397,  0.0000, -0.3420, -0.1000],
        [-0.1710,  0.8660, -0.4698,  0.0000],
        [ 0.2962,  0.5000,  0.8138,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.18831634521484 ms    means3D 2.6848316192626953 ms    allocate 7.155418395996094 ms    temp_mem_buffer/sortouts_buffer 76.34639739990234 ms
Done! pre_grouping_ip takes : 53.269147872924805 ms
trying to : forward...
buffers take : 176.4984130859375 ms    sum acc_size 149.19519424438477 ms
render ip working time :  156.44550323486328 ms

time pg 

buffers take : 87.7232551574707 ms    means3D 2.9277801513671875 ms    allocate 7.269859313964844 ms    temp_mem_buffer/sortouts_buffer 77.52418518066406 ms
Done! pre_grouping_ip takes : 53.29251289367676 ms
trying to : forward...
buffers take : 178.36403846740723 ms    sum acc_size 148.47278594970703 ms
render ip working time :  149.53017234802246 ms

time pg  160.45475006103516 ms
time fw  330.60431480407715 ms
time ol_forward  509.1242790222168 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.939693,0.000000,-0.342020,-0.200000,-0.171010,0.866026,-0.469846,0.000000,0.296198,0.500000,0.813798,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9397,  0.0000, -0.3420, -0.2000],
        [-0.1710,  0.8660, -0.4698,  0.0000],
        [ 0.2962,  0.5000,  0.8138,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.41624450683594 ms    means3D 2.7489662170410156 ms    allocate 7.145881652832031 ms    temp_mem_buffer/sortouts_bu

buffers take : 88.20486068725586 ms    means3D 2.8591156005859375 ms    allocate 7.214784622192383 ms    temp_mem_buffer/sortouts_buffer 78.12976837158203 ms
Done! pre_grouping_ip takes : 53.11703681945801 ms
trying to : forward...
buffers take : 174.68667030334473 ms    sum acc_size 148.68426322937012 ms
render ip working time :  161.14377975463867 ms

time pg  160.75944900512695 ms
time fw  338.50789070129395 ms
time ol_forward  517.2483921051025 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,-0.200000,0.000000,0.866026,-0.500000,0.000000,0.000000,0.500000,0.866026,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000, -0.2000],
        [ 0.0000,  0.8660, -0.5000,  0.0000],
        [ 0.0000,  0.5000,  0.8660,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.4875316619873 ms    means3D 2.8548240661621094 ms    allocate 7.1201324462890625 ms    temp_mem_buffer/sortouts_buf

buffers take : 88.74344825744629 ms    means3D 2.7227401733398438 ms    allocate 8.748769760131836 ms    temp_mem_buffer/sortouts_buffer 77.2705078125 ms
Done! pre_grouping_ip takes : 52.96492576599121 ms
trying to : forward...
buffers take : 178.98797988891602 ms    sum acc_size 152.97317504882812 ms
render ip working time :  142.18926429748535 ms

time pg  160.96758842468262 ms
time fw  323.98343086242676 ms
time ol_forward  503.13615798950195 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000000,0.000000,0.000000,-0.400000,0.000000,0.819152,-0.573577,0.000000,0.000000,0.573577,0.819153,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000, -0.4000],
        [ 0.0000,  0.8192, -0.5736,  0.0000],
        [ 0.0000,  0.5736,  0.8192,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.45455741882324 ms    means3D 2.667665481567383 ms    allocate 7.208824157714844 ms    temp_mem_buffer/sortouts_buffer 

buffers take : 87.35156059265137 ms    means3D 2.637624740600586 ms    allocate 7.173061370849609 ms    temp_mem_buffer/sortouts_buffer 77.53968238830566 ms
Done! pre_grouping_ip takes : 53.01070213317871 ms
trying to : forward...
buffers take : 174.67117309570312 ms    sum acc_size 148.62442016601562 ms
render ip working time :  158.64801406860352 ms

time pg  159.6853733062744 ms
time fw  336.0445499420166 ms
time ol_forward  513.7178897857666 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.965926,0.000000,0.258819,-0.400000,0.148453,0.819152,-0.554033,0.000000,-0.212012,0.573577,0.791241,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9659,  0.0000,  0.2588, -0.4000],
        [ 0.1485,  0.8192, -0.5540,  0.0000],
        [-0.2120,  0.5736,  0.7912,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.58432960510254 ms    means3D 3.0260086059570312 ms    allocate 7.176637649536133 ms    temp_mem_buffer/sortouts_buffe

buffers take : 87.91756629943848 ms    means3D 2.6597976684570312 ms    allocate 8.087635040283203 ms    temp_mem_buffer/sortouts_buffer 77.16870307922363 ms
Done! pre_grouping_ip takes : 53.10797691345215 ms
trying to : forward...
buffers take : 174.93844032287598 ms    sum acc_size 148.88811111450195 ms
render ip working time :  183.7470531463623 ms

time pg  160.3085994720459 ms
time fw  361.36651039123535 ms
time ol_forward  539.9913787841797 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.965926,0.000000,0.258819,-0.350000,0.148453,0.819152,-0.554033,0.000000,-0.212012,0.573577,0.791241,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9659,  0.0000,  0.2588, -0.3500],
        [ 0.1485,  0.8192, -0.5540,  0.0000],
        [-0.2120,  0.5736,  0.7912,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.70687675476074 ms    means3D 2.656221389770508 ms    allocate 7.354736328125 ms    temp_mem_buffer/sortouts_buffer 7

buffers take : 88.74368667602539 ms    means3D 3.766298294067383 ms    allocate 7.415294647216797 ms    temp_mem_buffer/sortouts_buffer 77.5609016418457 ms
Done! pre_grouping_ip takes : 53.269386291503906 ms
trying to : forward...
buffers take : 173.94471168518066 ms    sum acc_size 147.97329902648926 ms
render ip working time :  177.5069236755371 ms

time pg  161.17477416992188 ms
time fw  354.0968894958496 ms
time ol_forward  533.3065986633301 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:1.000001,0.000000,0.000000,-0.200000,0.000000,0.819152,-0.573577,0.000000,0.000000,0.573577,0.819153,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 1.0000,  0.0000,  0.0000, -0.2000],
        [ 0.0000,  0.8192, -0.5736,  0.0000],
        [ 0.0000,  0.5736,  0.8192,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 92.20218658447266 ms    means3D 6.890296936035156 ms    allocate 7.616758346557617 ms    temp_mem_buffer/sortouts_buffer 

接收到的数据: w2c_matrix:0.996195,0.015134,-0.085832,-0.200000,-0.049990,0.905929,-0.420469,0.000000,0.071394,0.423160,0.903239,0.200000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9962,  0.0151, -0.0858, -0.2000],
        [-0.0500,  0.9059, -0.4205,  0.0000],
        [ 0.0714,  0.4232,  0.9032,  0.2000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.56789970397949 ms    means3D 5.892276763916016 ms    allocate 7.312774658203125 ms    temp_mem_buffer/sortouts_buffer 76.36165618896484 ms
Done! pre_grouping_ip takes : 53.00498008728027 ms
trying to : forward...
buffers take : 175.9943962097168 ms    sum acc_size 149.02687072753906 ms
render ip working time :  161.35907173156738 ms

time pg  161.00311279296875 ms
time fw  339.9653434753418 ms
time ol_forward  518.9337730407715 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.996195,0.015134,-0.085832,-0.200000,-0.049990,0.905929,-0.420469,0.000000,0.071394,0.423160,0.903239,0.150000,0.0

buffers take : 176.4686107635498 ms    sum acc_size 149.33323860168457 ms
render ip working time :  159.9578857421875 ms

time pg  159.55686569213867 ms
time fw  339.02502059936523 ms
time ol_forward  516.4904594421387 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.966156,0.015134,-0.257515,-0.100000,-0.122245,0.905929,-0.405400,0.000000,0.227155,0.423160,0.877119,0.100000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9662,  0.0151, -0.2575, -0.1000],
        [-0.1222,  0.9059, -0.4054,  0.0000],
        [ 0.2272,  0.4232,  0.8771,  0.1000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.39025688171387 ms    means3D 2.904653549194336 ms    allocate 7.124900817871094 ms    temp_mem_buffer/sortouts_buffer 76.35903358459473 ms
Done! pre_grouping_ip takes : 53.01809310913086 ms
trying to : forward...
buffers take : 175.09055137634277 ms    sum acc_size 148.59366416931152 ms
render ip working time :  160.9053611755371 ms

time pg  15

buffers take : 87.19897270202637 ms    means3D 2.633810043334961 ms    allocate 7.137060165405273 ms    temp_mem_buffer/sortouts_buffer 77.42691040039062 ms
Done! pre_grouping_ip takes : 53.1306266784668 ms
trying to : forward...
buffers take : 173.42877388000488 ms    sum acc_size 147.385835647583 ms
render ip working time :  151.34716033935547 ms

time pg  159.55686569213867 ms
time fw  327.43167877197266 ms
time ol_forward  505.02824783325195 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.999885,0.015134,0.001319,-0.100000,-0.013154,0.905929,-0.423226,0.000000,-0.007600,0.423160,0.906024,0.150000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9999,  0.0151,  0.0013, -0.1000],
        [-0.0132,  0.9059, -0.4232,  0.0000],
        [-0.0076,  0.4232,  0.9060,  0.1500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.02294731140137 ms    means3D 2.7818679809570312 ms    allocate 7.328510284423828 ms    temp_mem_buffer/sortouts_buff

buffers take : 91.11595153808594 ms    means3D 4.959583282470703 ms    allocate 8.093118667602539 ms    temp_mem_buffer/sortouts_buffer 78.06205749511719 ms
Done! pre_grouping_ip takes : 53.22694778442383 ms
trying to : forward...
buffers take : 174.35836791992188 ms    sum acc_size 148.37408065795898 ms
render ip working time :  174.55410957336426 ms

time pg  163.6648178100586 ms
time fw  351.5818119049072 ms
time ol_forward  533.1816673278809 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.999885,0.015134,-0.001329,-0.100000,-0.013154,0.818674,-0.574109,0.000000,-0.007600,0.574060,0.818779,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9999,  0.0151, -0.0013, -0.1000],
        [-0.0132,  0.8187, -0.5741,  0.0000],
        [-0.0076,  0.5741,  0.8188,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 90.1646614074707 ms    means3D 4.476070404052734 ms    allocate 8.393287658691406 ms    temp_mem_buffer/sortouts_buffe

接收到的数据: w2c_matrix:0.996311,0.014960,0.084513,-0.100000,0.042961,0.765521,-0.641975,0.000000,-0.074300,0.643237,0.762055,0.350000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9963,  0.0150,  0.0845, -0.1000],
        [ 0.0430,  0.7655, -0.6420,  0.0000],
        [-0.0743,  0.6432,  0.7621,  0.3500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.669921875 ms    means3D 2.656221389770508 ms    allocate 7.308244705200195 ms    temp_mem_buffer/sortouts_buffer 76.70378684997559 ms
Done! pre_grouping_ip takes : 53.131818771362305 ms
trying to : forward...
buffers take : 176.87153816223145 ms    sum acc_size 149.77073669433594 ms
render ip working time :  175.17852783203125 ms

time pg  158.22315216064453 ms
time fw  354.6407222747803 ms
time ol_forward  530.9674739837646 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.996311,0.014960,0.084513,-0.100000,0.042961,0.765521,-0.641975,0.000000,-0.074300,0.643237,0.762055,0.350000,0.000000

buffers take : 175.79317092895508 ms    sum acc_size 148.88763427734375 ms
render ip working time :  162.42504119873047 ms

time pg  160.2327823638916 ms
time fw  341.0663604736328 ms
time ol_forward  519.2468166351318 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.965467,0.007537,-0.260419,-0.100000,-0.155543,0.818560,-0.552962,0.000000,0.209001,0.574372,0.791465,0.350000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9655,  0.0075, -0.2604, -0.1000],
        [-0.1555,  0.8186, -0.5530,  0.0000],
        [ 0.2090,  0.5744,  0.7915,  0.3500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.68231964111328 ms    means3D 2.961397171020508 ms    allocate 7.364511489868164 ms    temp_mem_buffer/sortouts_buffer 76.3552188873291 ms
Done! pre_grouping_ip takes : 53.272247314453125 ms
trying to : forward...
buffers take : 175.77028274536133 ms    sum acc_size 148.90742301940918 ms
render ip working time :  162.40715980529785 ms

time pg  1

buffers take : 176.62906646728516 ms    sum acc_size 149.6295928955078 ms
render ip working time :  162.84775733947754 ms

time pg  158.10751914978027 ms
time fw  342.0696258544922 ms
time ol_forward  518.2149410247803 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.965467,0.030206,-0.258771,-0.100000,-0.155543,0.863639,-0.479515,0.000000,0.209001,0.503206,0.838513,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9655,  0.0302, -0.2588, -0.1000],
        [-0.1555,  0.8636, -0.4795,  0.0000],
        [ 0.2090,  0.5032,  0.8385,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.99846267700195 ms    means3D 2.6967525482177734 ms    allocate 7.37762451171875 ms    temp_mem_buffer/sortouts_buffer 76.92217826843262 ms
Done! pre_grouping_ip takes : 53.194284439086914 ms
trying to : forward...
buffers take : 176.4395236968994 ms    sum acc_size 149.37686920166016 ms
render ip working time :  162.83893585205078 ms

time pg  1

buffers take : 87.25786209106445 ms    means3D 3.716707229614258 ms    allocate 7.149457931518555 ms    temp_mem_buffer/sortouts_buffer 76.39026641845703 ms
Done! pre_grouping_ip takes : 53.08890342712402 ms
trying to : forward...
buffers take : 179.55541610717773 ms    sum acc_size 153.64789962768555 ms
render ip working time :  167.58990287780762 ms

time pg  159.4533920288086 ms
time fw  349.7602939605713 ms
time ol_forward  527.1904468536377 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.982843,0.052644,0.176776,-0.100000,0.029100,0.902145,-0.430451,0.000000,-0.182138,0.428209,0.885135,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9828,  0.0526,  0.1768, -0.1000],
        [ 0.0291,  0.9021, -0.4305,  0.0000],
        [-0.1821,  0.4282,  0.8851,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 88.3328914642334 ms    means3D 2.8994083404541016 ms    allocate 7.639884948730469 ms    temp_mem_buffer/sortouts_buffer

buffers take : 88.64712715148926 ms    means3D 3.9398670196533203 ms    allocate 7.280826568603516 ms    temp_mem_buffer/sortouts_buffer 77.42500305175781 ms
Done! pre_grouping_ip takes : 53.02071571350098 ms
trying to : forward...
buffers take : 178.73287200927734 ms    sum acc_size 152.73213386535645 ms
render ip working time :  163.88440132141113 ms

time pg  160.9480381011963 ms
time fw  345.306396484375 ms
time ol_forward  524.2373943328857 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.981700,0.097299,0.163707,-0.100000,0.016011,0.814417,-0.580060,0.000000,-0.189765,0.572065,0.797956,0.250000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9817,  0.0973,  0.1637, -0.1000],
        [ 0.0160,  0.8144, -0.5801,  0.0000],
        [-0.1898,  0.5721,  0.7980,  0.2500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.3403549194336 ms    means3D 2.6426315307617188 ms    allocate 7.172107696533203 ms    temp_mem_buffer/sortouts_buffer

buffers take : 89.80226516723633 ms    means3D 4.925251007080078 ms    allocate 7.268190383911133 ms    temp_mem_buffer/sortouts_buffer 77.60763168334961 ms
Done! pre_grouping_ip takes : 52.92153358459473 ms
trying to : forward...
buffers take : 174.61180686950684 ms    sum acc_size 148.39434623718262 ms
render ip working time :  157.3629379272461 ms

time pg  162.52565383911133 ms
time fw  334.6278667449951 ms
time ol_forward  515.1431560516357 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.992232,0.097299,0.077524,-0.150000,-0.034606,0.814417,-0.579248,0.000000,-0.119497,0.572065,0.811459,0.100000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9922,  0.0973,  0.0775, -0.1500],
        [-0.0346,  0.8144, -0.5792,  0.0000],
        [-0.1195,  0.5721,  0.8115,  0.1000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.50352668762207 ms    means3D 5.981683731079102 ms    allocate 7.167577743530273 ms    temp_mem_buffer/sortouts_buffe

buffers take : 90.30485153198242 ms    means3D 5.486726760864258 ms    allocate 7.287740707397461 ms    temp_mem_buffer/sortouts_buffer 77.5289535522461 ms
Done! pre_grouping_ip takes : 53.14373970031738 ms
trying to : forward...
buffers take : 174.59559440612793 ms    sum acc_size 148.63848686218262 ms
render ip working time :  147.5064754486084 ms

time pg  162.69826889038086 ms
time fw  324.770450592041 ms
time ol_forward  505.43904304504395 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.958908,0.097299,-0.266515,-0.150000,-0.230633,0.814417,-0.532479,0.000000,0.165245,0.572065,0.803392,0.100000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9589,  0.0973, -0.2665, -0.1500],
        [-0.2306,  0.8144, -0.5325,  0.0000],
        [ 0.1652,  0.5721,  0.8034,  0.1000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.42618560791016 ms    means3D 2.696514129638672 ms    allocate 7.224559783935547 ms    temp_mem_buffer/sortouts_buffer

buffers take : 87.94355392456055 ms    means3D 4.421234130859375 ms    allocate 7.104635238647461 ms    temp_mem_buffer/sortouts_buffer 76.4162540435791 ms
Done! pre_grouping_ip takes : 52.924394607543945 ms
trying to : forward...
buffers take : 174.37744140625 ms    sum acc_size 148.37360382080078 ms
render ip working time :  148.89073371887207 ms

time pg  160.1097583770752 ms
time fw  326.05648040771484 ms
time ol_forward  504.2243003845215 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097299,-0.009250,-0.150000,-0.084959,0.814417,-0.574028,0.000000,-0.048319,0.572065,0.818786,0.100000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9952,  0.0973, -0.0093, -0.1500],
        [-0.0850,  0.8144, -0.5740,  0.0000],
        [-0.0483,  0.5721,  0.8188,  0.1000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.16592597961426 ms    means3D 5.295515060424805 ms    allocate 7.365942001342773 ms    temp_mem_buffer/sortouts_buffer

buffers take : 86.86947822570801 ms    means3D 2.74658203125 ms    allocate 7.287502288818359 ms    temp_mem_buffer/sortouts_buffer 76.83420181274414 ms
Done! pre_grouping_ip takes : 53.208112716674805 ms
trying to : forward...
buffers take : 173.44355583190918 ms    sum acc_size 147.45402336120605 ms
render ip working time :  168.66660118103027 ms

time pg  159.35873985290527 ms
time fw  344.79641914367676 ms
time ol_forward  522.1450328826904 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097427,0.007786,-0.150000,-0.084959,0.901724,-0.423885,0.000000,-0.048319,0.421193,0.905685,0.300000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9952,  0.0974,  0.0078, -0.1500],
        [-0.0850,  0.9017, -0.4239,  0.0000],
        [-0.0483,  0.4212,  0.9057,  0.3000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 86.30490303039551 ms    means3D 2.7055740356445312 ms    allocate 7.176637649536133 ms    temp_mem_buffer/sortouts_buffe

buffers take : 88.19246292114258 ms    means3D 2.6750564575195312 ms    allocate 7.445096969604492 ms    temp_mem_buffer/sortouts_buffer 78.07087898254395 ms
Done! pre_grouping_ip takes : 53.385019302368164 ms
trying to : forward...
buffers take : 174.896240234375 ms    sum acc_size 148.81086349487305 ms
render ip working time :  177.24871635437012 ms

time pg  161.00335121154785 ms
time fw  354.7933101654053 ms
time ol_forward  533.8253974914551 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.150000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.550000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.5000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  5.5000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 86.11559867858887 ms    means3D 2.6085376739501953 ms

buffers take : 174.65829849243164 ms    sum acc_size 148.6227512359619 ms
render ip working time :  181.29611015319824 ms

time pg  159.27553176879883 ms
time fw  358.6103916168213 ms
time ol_forward  535.8777046203613 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.980221,0.097735,0.172093,-0.250000,0.003306,0.861348,-0.508006,0.000000,-0.197882,0.498526,0.843989,0.550000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9802,  0.0977,  0.1721, -0.2500],
        [ 0.0033,  0.8613, -0.5080,  0.0000],
        [-0.1979,  0.4985,  0.8440,  0.5500],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 87.00704574584961 ms    means3D 2.7430057525634766 ms    allocate 7.254838943481445 ms    temp_mem_buffer/sortouts_buffer 77.00777053833008 ms
Done! pre_grouping_ip takes : 53.18331718444824 ms
trying to : forward...
buffers take : 176.76544189453125 ms    sum acc_size 149.6729850769043 ms
render ip working time :  181.30040168762207 ms

time pg  15

buffers take : 89.07485008239746 ms    means3D 4.3239593505859375 ms    allocate 7.180213928222656 ms    temp_mem_buffer/sortouts_buffer 77.56924629211426 ms
Done! pre_grouping_ip takes : 53.30920219421387 ms
trying to : forward...
buffers take : 174.36790466308594 ms    sum acc_size 148.3621597290039 ms
render ip working time :  186.96022033691406 ms

time pg  161.62633895874023 ms
time fw  364.0007972717285 ms
time ol_forward  543.6034202575684 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.991490,0.097735,0.086007,-0.250000,-0.040982,0.861348,-0.506361,0.000000,-0.123571,0.498526,0.858024,0.500000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 0.9915,  0.0977,  0.0860, -0.2500],
        [-0.0410,  0.8613, -0.5064,  0.0000],
        [-0.1236,  0.4985,  0.8580,  0.5000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
trying to : pre grouping...
buffers take : 89.52832221984863 ms    means3D 5.323171615600586 ms    allocate 7.44938850402832 ms    temp_mem_buffer/sortouts_buffe

buffers take : 87.47386932373047 ms    means3D 2.753734588623047 ms    allocate 7.122039794921875 ms    temp_mem_buffer/sortouts_buffer 77.59666442871094 ms
Done! pre_grouping_ip takes : 53.37238311767578 ms
trying to : forward...
buffers take : 174.4365692138672 ms    sum acc_size 148.0729579925537 ms
render ip working time :  180.2215576171875 ms

time pg  160.25424003601074 ms
time fw  357.32269287109375 ms
time ol_forward  535.607099533081 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.500000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  5.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 88.85931968688965 ms    means3D 5.203008651733398 ms    

buffers take : 176.3138771057129 ms    sum acc_size 149.31821823120117 ms
render ip working time :  192.59166717529297 ms

time pg  159.95049476623535 ms
time fw  371.5035915374756 ms
time ol_forward  549.3695735931396 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  4.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 87.46027946472168 ms    means3D 2.6819705963134766 ms    allocate 7.09223747253418 ms    temp_mem_buffer/sortouts_buffer 77.68464088439941 ms
Done! pre_grouping_ip takes : 53.30228805541992 ms
trying to : forward...
buffers take : 174.3948459625244 ms    sum acc_size 148.1699943542480

buffers take : 174.84712600708008 ms    sum acc_size 148.75078201293945 ms
render ip working time :  192.5973892211914 ms

time pg  160.21013259887695 ms
time fw  370.147705078125 ms
time ol_forward  548.3639240264893 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  4.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 87.15605735778809 ms    means3D 2.7167797088623047 ms    allocate 7.259845733642578 ms    temp_mem_buffer/sortouts_buffer 77.1780014038086 ms
Done! pre_grouping_ip takes : 53.12013626098633 ms
trying to : forward...
buffers take : 176.0404109954834 ms    sum acc_size 149.04308319091797

buffers take : 176.1929988861084 ms    sum acc_size 149.80530738830566 ms
render ip working time :  192.57020950317383 ms

time pg  159.8832607269287 ms
time fw  371.45471572875977 ms
time ol_forward  549.3412017822266 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  4.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 86.38978004455566 ms    means3D 2.726316452026367 ms    allocate 7.1659088134765625 ms    temp_mem_buffer/sortouts_buffer 76.49588584899902 ms
Done! pre_grouping_ip takes : 53.08866500854492 ms
trying to : forward...
buffers take : 176.49579048156738 ms    sum acc_size 149.56235885620

buffers take : 174.6349334716797 ms    sum acc_size 148.60248565673828 ms
render ip working time :  192.5961971282959 ms

time pg  160.66765785217285 ms
time fw  369.9078559875488 ms
time ol_forward  548.5854148864746 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  4.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 87.36443519592285 ms    means3D 2.663135528564453 ms    allocate 7.11822509765625 ms    temp_mem_buffer/sortouts_buffer 77.58140563964844 ms
Done! pre_grouping_ip takes : 53.27796936035156 ms
trying to : forward...
buffers take : 174.97587203979492 ms    sum acc_size 148.63252639770508

buffers take : 176.04899406433105 ms    sum acc_size 149.07145500183105 ms
render ip working time :  192.5833225250244 ms

time pg  157.7448844909668 ms
time fw  371.4406490325928 ms
time ol_forward  547.0924377441406 ms
已向 192.168.5.7 发送确认消息
接收到的数据: w2c_matrix:0.995213,0.097735,-0.000735,-0.100000,-0.084959,0.861348,-0.500862,0.000000,-0.048319,0.498526,0.865529,0.400000,0.000000,0.000000,0.000000,1.000000
成功解析w2c矩阵:
tensor([[ 9.9521e-01,  9.7735e-02, -7.3500e-04, -1.0000e-01],
        [-8.4959e-02,  8.6135e-01, -5.0086e-01,  0.0000e+00],
        [-4.8319e-02,  4.9853e-01,  8.6553e-01,  4.0000e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
trying to : pre grouping...
buffers take : 89.70046043395996 ms    means3D 6.0062408447265625 ms    allocate 7.325649261474609 ms    temp_mem_buffer/sortouts_buffer 76.36666297912598 ms
Done! pre_grouping_ip takes : 53.122520446777344 ms
trying to : forward...
buffers take : 176.25904083251953 ms    sum acc_size 149.31392669677

KeyboardInterrupt: 

In [8]:
recv_sock.close()
send_sock.close()